#!/usr/bin/env fish
# set -g fish_trace 1
set -g temp_files
set -g docker_compose_directory ""
set -g docker_compose_action_timeout 120
set -g docker_compose_healthy_wait_timeout 600
set -g docker_backup_service_path ".docker/backup/service"

function create
    set -l source "$argv[2]"
    set -l target "$argv[1]"
    set -e argv[1..2]

    if not test_writeable "$target"
        log_error "Target directory '$target' is not writable or does not exist."
        exit 1
    end

    if not test_readable "$source"
        log_error "Source directory '$source' is not readable or does not exist."
        exit 1
    end
    
    set -l temp (mktemp --directory --tmpdir="$target")
    set -a temp_files $temp
    
    set -l last_dar (find_last_archive "$target")

    save_docker_compose_state "$source"

    # dar directly opens the target files using special filesystem performance flags that unprivileged user namespaces (rootlesskit) actively block. Use -aa tag to block read ataime
    set -l common_flags "-aa" "-Q" "--no-overwrite" "--compress=zstd"
    if test -z "$last_dar"
        set -l name "full"
        log_info "Creating full archive: '$name'"
        set dar_output (dar --create "$temp/$name" --fs-root "$source" $common_flags $argv 2>&1 | string collect)
        if test $status -ne 0
            log_error "Failed to create full archive: '$name'"
            log_error "$dar_output"
            exit 1
        end
    else
        set -l last_ref (string replace -r '\.[^.]+\.[^.]+$' '' $last_dar)
        set -l name "incremental-"(date +%Y%m%d-%H%M%S)
        log_info "Creating incremental archive '$name' based on '$last_ref'."
        set dar_output (dar --create "$temp/$name" --ref "$last_ref" --fs-root "$source" $common_flags $argv 2>&1 | string collect)
        if test $status -ne 0
            log_error "Failed to create incremental archive: '$name'"
            log_error "$dar_output"
            exit 1
        end
    end

    restore_docker_compose_state

    set -l size (du --total --bytes "$temp" | tail -n 1 | cut -f 1)
    set -l count (find "$temp" -type f | wc -l)
    
    if not mv "$temp"/* "$target"
        log_error "Failed to move created archive to persistent storage."
        exit 1
    end

    log_success "Archive created successfully."
    log_info "Archive size: $size bytes"
    log_info "Total files: $count"
end

function extract
    set -l archive_dir "$argv[1]"
    set -l target "$argv[2]"
    set -e argv[1..2]

    if not test_readable "$archive_dir"
        log_error "Archive directory '$archive_dir' is not readable or does not exist."
        exit 1
    end

    if not test_writeable "$target"
        log_error "Target directory '$target' is not writable or does not exist."
        exit 1
    end

    set -l count (get_archives "$archive_dir" | wc -l)
    if test $count -eq 0
        log_error "No archives found inside target directory."
        exit 2
    end
    
    save_docker_compose_state "$target"

    set -l index 0
    get_archives "$archive_dir" | while read -l archive_basename
        set index (math $index + 1)
        log_info "[$index/$count] Extracting '$archive_basename'..."
        if not dar -x "$archive_dir/$archive_basename" --fs-root="$target" -Q --quiet -w -ae $argv
            log_error "[$index/$count] Extraction of '$archive_basename' failed."
            exit 1
        end
    end

    restore_docker_compose_state

    log_success "Extraction completed successfully."
end

function verify
    set -l archive_dir "$argv[1]"
    set -e argv[1]
    
    if not test_readable "$archive_dir"
        log_error "Archive directory '$archive_dir' is not readable or does not exist."
        exit 1
    end

    set -l total (get_archives "$archive_dir" | wc -l)
    
    if test $total -eq 0
        log_error "No archives found inside target directory."
        exit 2
    end

    set -l index 0
    get_archives "$archive_dir" | while read -l archive_basename
        set index (math $index + 1)
        
        log_info "[$index/$total] Verifying '$archive_basename'..."
        if not dar --test "$archive_dir/$archive_basename" -Q --quiet $argv
            log_error "[$index/$total] Verification of '$archive_basename' failed."
            exit 1
        end
    end
    log_success "Verification passed. No errors found."
end

function compare
    set -l archive_dir "$argv[1]"
    set -l source "$argv[2]"
    set -l temp_dir "$argv[3]"
    set -e argv[1..3]

    if not test_readable "$archive_dir"
        log_error "Archive directory '$archive_dir' is not readable or does not exist."
        exit 1
    end
    
    if not test_readable "$source"
        log_error "Source directory '$source' is not readable or does not exist."
        exit 1
    end

    if not test_writeable "$temp_dir"
        log_error "Temporary directory '$temp_dir' is not writable or does not exist."
        exit 1
    end
    
    set -l temp (mktemp --directory --tmpdir="$temp_dir")
    set -a temp_files $temp
    set -l source_temp "$temp/source"
    set -l archive_temp "$temp/archive"
    mkdir "$source_temp" "$archive_temp"

    save_docker_compose_state "$source"

    log_info "Creating temporary copy of source directory..."
    cp -r "$source/." "$source_temp"

    restore_docker_compose_state

    log_info "Extracting files from archive..."
    extract "$archive_dir" "$archive_temp" -O $argv
    
    set results (diff -rq "$source_temp" "$archive_temp" | grep -vE " is a socket|Special file" 2>&1 | string collect)

    if test (count $results) -gt 0
        log_error "Mismatches discovered: Source and archive files are not equal."
        printf "%s\n" $results
        exit 1
    end
    log_success "Verification passed: Source and archive files match perfectly."
end

function save_docker_compose_state
    set -l service_script "$argv[1]/$docker_backup_service_path"
    if test ! -f "$service_script"
        return 0
    end
    if test ! -x "$service_script"
        log_error "Docker Compose service script not executable."
        exit 1
    end
    log_checking "Detecting Docker Compose containers state..."
    if is_docker_compose_stopped "$service_script"
        log_info "Docker Compose containers is not running."
        return 0
    end
    log_info "Docker Compose containers is running."
    set -g docker_compose_directory "$argv[1]"
    log_info "Stopping Docker Compose containers..."
    if not stop_docker_containers "$service_script"
        log_error "Failed to stop Docker Compose containers."
        exit 1
    end
    log_info "Docker Compose containers stopped. Restart event queued."
end

function restore_docker_compose_state
    test -z "$docker_compose_directory"; and return 0
    log_info "Executing queued Docker Compose containers restart..."
    set -l service_script "$docker_compose_directory/$docker_backup_service_path"
    if not start_docker_containers "$service_script"
        log_error "Failed to restart Docker Compose containers."
        exit 1
    end

    log_checking "Waiting for Docker Compose containers is running and healthy (if applicable)"
    set -l healthy 0
    set -l previous_output ""
    set -l start_time (date +%s)

    while test "$healthy" -eq 0
        set -l output (is_docker_compose_healthy "$service_script")
        if test -z "$output"
            log_info "Docker Compose containers is running and healthy"
            set healthy 1
            continue
        else
            if test "$previous_output" != "$output"
                set previous_output "$output"
                log_info "Docker Compose containers state changed to $output"
            end
        end
        
        # Calculate time elapsed using date timestamps
        set -l current_time (date +%s)
        set -l time_elapsed (math $current_time - $start_time)
        
        if test $time_elapsed -ge $docker_compose_healthy_wait_timeout
            log_error "Timed out waiting for Docker Compose containers healthy state after $time_elapsed seconds."
            exit 1
        end
        sleep 1
    end
    set -g docker_compose_directory ""
end

function is_docker_compose_stopped
    set -l state (timeout $docker_compose_action_timeout "$argv[1]" status)
    test "$state" = "none"; and return 0
    return 1
end

function is_docker_compose_healthy
    not timeout $docker_compose_action_timeout "$argv[1]" status; and return 1
    return 0
end

function start_docker_containers
    timeout $docker_compose_action_timeout "$argv[1]" start
    return $status
end

function stop_docker_containers
    timeout $docker_compose_action_timeout "$argv[1]" stop; and return 0
    return 1
end

function get_archives
    find "$argv[1]" -maxdepth 1 -type f -name "*.*.dar" | grep -oP '[^/]+(?=\.\d+\.dar)' | sort | uniq
end

function find_last_archive
    find "$argv[1]" -maxdepth 1 -type f -name "*.*.dar" -printf '%T@\t%p\n' | sort -n | tail -1 | cut -f2-
end

function test_readable
    test -r "$argv[1]"
end

function test_writeable
    test -w "$argv[1]"
end

function remove
    rm -rf $argv
end

function log_info
    set_color cyan; echo -s "ℹ️  Info:     " $argv; set_color normal
end

function log_success
    set_color green; echo -s "✅ Success:  " $argv; set_color normal
end

function log_error
    set_color red; echo -s "❌ Error:    " $argv; set_color normal
end

function log_checking
    set_color cyan; echo -s "🔍 Checking: " $argv; set_color normal
end

function on_exit --on-event fish_exit
    if test -n "$docker_compose_directory"
        log_error "Exiting while a Docker Compose restart was still pending."
        set -l service_script "$docker_compose_directory/$docker_backup_service_path"
        start_docker_containers "$service_script"
        log_info "Docker Compose restart command sent."
    end
    set -l count (count $temp_files)
    if test $count -gt 0
        log_info "Cleaning up $count temporary workspace files or directories..."
        rm -rf $temp_files
    end
end

set -l action $argv[1]
set -e argv[1]


switch "$action"
    case create
        create $argv
    case extract
        extract $argv
    case verify
        verify $argv
    case compare
        compare $argv
    case '*'
        echo ""
        echo "Usage:"
        echo "  $_ create  <target_dir> <source_dir> [dar_flags...]  - Create full or incremental backup"
        echo "  $_ extract <archive_dir> <target_dir> [dar_flags...] - Extract archives sequentially"
        echo "  $_ verify  <archive_dir> [dar_flags...]              - Test integrity of archives"
        echo "  $_ compare <archive_dir> <source_dir> <temp_dir>     - Compare filesystem state against archives using temporary directory"
        exit 1
end
